apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileservice-deployment
spec:
  selector:
    matchLabels:
      app: fileservice
  replicas: 1
  template:
    metadata:
      labels:
        app: fileservice
    spec:
      containers:
        - name: fileservice
          image: proselyte/fileservice
          volumeMounts:
            - mountPath: /app/storage
              name: fileservice-volume
          env:
            - name: STORAGE_LOCATION
              valueFrom:
                secretKeyRef: # Используем secretKeyRef вместо configMapKeyRef
                  name: fileservice-secret  # Указываем имя секрета
                  key: .FILESERVICE_STORAGE_LOCATION  # Указываем ключ в секрете, начинающийся с точки
      volumes:
        - name: fileservice-volume
          persistentVolumeClaim:
            claimName: local-persistent-volume-claim
