apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileservice-deployment
spec:
  selector:
    matchLabels:
      app: fileservice
  replicas: 1
  template:
    metadata:
      labels:
        app: fileservice
    spec:
      containers:
        - name: fileservice
          image: proselyte/fileservice
          volumeMounts:
            - mountPath: /app/storage
              name: fileservice-volume
          env:
            - name: STORAGE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: fileservice-configmap
                  key: FILESERVICE_STORAGE_LOCATION  # Удалены кавычки вокруг ключа
      volumes:
        - name: fileservice-volume
          persistentVolumeClaim:
            claimName: local-persistent-volume-claim
