apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-persistent-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /storage
    type: DirectoryOrCreate

