apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-persistent-volume-claim
spec:
  volumeName: local-persistent-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

